### ISSUE TITLE
Problems with long small "i" in Latvian language while using Google chrome

### ISSUE THREAD

**Issue by Gberzi01** [googlefonts/mavenproFont#14]
Long small ­­`i` (`ī`) has issues with its "roof" going over to the next character in Google chrome for the font. Google chrome version 118.0.5993.89, on Windows 11.

Steps to reproduce the behavior.

1. Open https://fonts.google.com/specimen/Maven+Pro?preview.text=p%C4%AB in Google chrome

Expected text is "pī". Other "long" vowels (ē, ū, ā) do not have this issue - https://fonts.google.com/specimen/Maven+Pro?preview.text=p%C4%AB%20p%C4%93%20p%C5%AB%20p%C4%81

The issue was originally posted on google fonts [github](https://github.com/google/fonts/issues/6886) repository, was told to also post here.

**Comment by moyogo** [comment]
This is not a Maven Pro bug, this is a GF bug.
